WIP - Upgrade Angular to V12
zowe/zlux-app-manager pull request #376
Opened 2021-10-07 14:45 UTC by DivergentEuropeans

## Proposed changes

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zlux/issues* if any]

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets the "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zlux/blob/master/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made
- [ ] Relevant update to CHANGELOG.md
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

Known Issues: Personalization menu is visually buggy, Notifications do not work, Angular Material snackbars are disabled

## Further comments

2021-10-07 14:45 UTC, DivergentEuropeans commented
Code is not ready for review yet

2021-11-15 10:06 UTC, lchudinov commented
@DivergentEuropeans please revert the changes for `fetch` back. I double checked that `response.json()` is needed.

2021-11-15 10:25 UTC, lchudinov requested changes
@DivergentEuropeans please revert the changes for `fetch()` back. I double checked that `response.json()` is needed.

2021-11-15 10:25 UTC, lchudinov commented on bootstrap/src/bootstrap/dsm-resources.ts
> +    return response;
Please revert the change back.

2021-11-15 10:25 UTC, lchudinov commented on bootstrap/src/bootstrap/rocket-mvd-resources.ts
> +    return response;
Please revert the change back.

2021-11-15 10:25 UTC, lchudinov commented on system-apps/web-browser-app/webClient/package.json
>      "@angular/cli": "~8.0.0",
Why we don't upgrade `angular/cli` ?

2021-11-16 04:11 UTC, lchudinov approved these changes

2021-12-01 21:58 UTC, DivergentEuropeans reviewed
This is not ready yet because snapshots and multiple app opens don't work

2021-12-13 20:49 UTC, merged